sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

script:
  - if [[ "$TRAVIS_TAG" ]] ; then
    docker image build . -t cubos/sdkgen -t cubos/sdkgen:$TRAVIS_TAG;
    else
    docker image build .;
    fi

deploy:
  provider: script
  skip_cleanup: true
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push cubos/sdkgen:$TRAVIS_TAG
  on:
    branch: master
    tags: true
