sudo: required

services:
  - docker

script:
  - docker build -t cubos/sdkgen -t cubos/sdkgen:"$TRAVIS_TAG" .

deploy:
  provider: script
  skip_cleanup: true
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push cubos/sdkgen
  on:
    branch: master
    tags: true
